config/routes.rb
Rails.application.routes.draw do
  root to: "souls#index"
  resources :public_talks
  resources :public_speakers
  resources :kingdom_halls
  resources :field_service_groups
  resources :congregations
  resources :contact_informations
  resources :publishers
  devise_for :users
  resources :souls
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/kingdom_hall.rb
class KingdomHall < ApplicationRecord
end

app/controllers/kingdom_halls_controller.rb
class KingdomHallsController < ApplicationController
  before_action :set_kingdom_hall, only: [:show, :edit, :update, :destroy]

  # GET /kingdom_halls
  # GET /kingdom_halls.json
  def index
    @kingdom_halls = KingdomHall.all
  end

  # GET /kingdom_halls/1
  # GET /kingdom_halls/1.json
  def show
  end

  # GET /kingdom_halls/new
  def new
    @kingdom_hall = KingdomHall.new
  end

  # GET /kingdom_halls/1/edit
  def edit
  end

  # POST /kingdom_halls
  # POST /kingdom_halls.json
  def create
    @kingdom_hall = KingdomHall.new(kingdom_hall_params)

    respond_to do |format|
      if @kingdom_hall.save
        format.html { redirect_to @kingdom_hall, notice: 'Kingdom hall was successfully created.' }
        format.json { render :show, status: :created, location: @kingdom_hall }
      else
        format.html { render :new }
        format.json { render json: @kingdom_hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kingdom_halls/1
  # PATCH/PUT /kingdom_halls/1.json
  def update
    respond_to do |format|
      if @kingdom_hall.update(kingdom_hall_params)
        format.html { redirect_to @kingdom_hall, notice: 'Kingdom hall was successfully updated.' }
        format.json { render :show, status: :ok, location: @kingdom_hall }
      else
        format.html { render :edit }
        format.json { render json: @kingdom_hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kingdom_halls/1
  # DELETE /kingdom_halls/1.json
  def destroy
    @kingdom_hall.destroy
    respond_to do |format|
      format.html { redirect_to kingdom_halls_url, notice: 'Kingdom hall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kingdom_hall
      @kingdom_hall = KingdomHall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kingdom_hall_params
      params.require(:kingdom_hall).permit(:address, :auditorium_count)
    end
end

app/helpers/kingdom_halls_helper.rb
module KingdomHallsHelper
end

app/views/kingdom_halls/_form.html.erb
<%= form_with(model: kingdom_hall, local: true) do |form| %>
  <% if kingdom_hall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kingdom_hall.errors.count, "error") %> prohibited this kingdom_hall from being saved:</h2>

      <ul>
        <% kingdom_hall.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :auditorium_count %>
    <%= form.number_field :auditorium_count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kingdom_halls/edit.html.erb
<h1>Editing Kingdom Hall</h1>

<%= render 'form', kingdom_hall: @kingdom_hall %>

<%= link_to 'Show', @kingdom_hall %> |
<%= link_to 'Back', kingdom_halls_path %>

app/views/kingdom_halls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kingdom Halls</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Auditorium count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kingdom_halls.each do |kingdom_hall| %>
      <tr>
        <td><%= kingdom_hall.address %></td>
        <td><%= kingdom_hall.auditorium_count %></td>
        <td><%= link_to 'Show', kingdom_hall %></td>
        <td><%= link_to 'Edit', edit_kingdom_hall_path(kingdom_hall) %></td>
        <td><%= link_to 'Destroy', kingdom_hall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kingdom Hall', new_kingdom_hall_path %>

app/views/kingdom_halls/new.html.erb
<h1>New Kingdom Hall</h1>

<%= render 'form', kingdom_hall: @kingdom_hall %>

<%= link_to 'Back', kingdom_halls_path %>

app/views/kingdom_halls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @kingdom_hall.address %>
</p>

<p>
  <strong>Auditorium count:</strong>
  <%= @kingdom_hall.auditorium_count %>
</p>

<%= link_to 'Edit', edit_kingdom_hall_path(@kingdom_hall) %> |
<%= link_to 'Back', kingdom_halls_path %>