config/routes.rb
Rails.application.routes.draw do
  root to: "souls#index"
  resources :public_talks
  resources :public_speakers
  resources :kingdom_halls
  resources :field_service_groups
  resources :congregations
  resources :contact_informations
  resources :publishers
  devise_for :users
  resources :souls
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/congregation.rb
class Congregation < ApplicationRecord
  has_many :publishers
  has_many :public_speakers
end

app/controllers/congregations_controller.rb
class CongregationsController < ApplicationController
  before_action :set_congregation, only: [:show, :edit, :update, :destroy]

  # GET /congregations
  # GET /congregations.json
  def index
    @congregations = Congregation.all
  end

  # GET /congregations/1
  # GET /congregations/1.json
  def show
  end

  # GET /congregations/new
  def new
    @congregation = Congregation.new
  end

  # GET /congregations/1/edit
  def edit
  end

  # POST /congregations
  # POST /congregations.json
  def create
    @congregation = Congregation.new(congregation_params)

    respond_to do |format|
      if @congregation.save
        format.html { redirect_to @congregation, notice: 'Congregation was successfully created.' }
        format.json { render :show, status: :created, location: @congregation }
      else
        format.html { render :new }
        format.json { render json: @congregation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /congregations/1
  # PATCH/PUT /congregations/1.json
  def update
    respond_to do |format|
      if @congregation.update(congregation_params)
        format.html { redirect_to @congregation, notice: 'Congregation was successfully updated.' }
        format.json { render :show, status: :ok, location: @congregation }
      else
        format.html { render :edit }
        format.json { render json: @congregation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /congregations/1
  # DELETE /congregations/1.json
  def destroy
    @congregation.destroy
    respond_to do |format|
      format.html { redirect_to congregations_url, notice: 'Congregation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_congregation
      @congregation = Congregation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def congregation_params
      params.require(:congregation).permit(:name, :congregation_number)
    end
end

app/helpers/congregations_helper.rb
module CongregationsHelper
end

app/views/congregations/_form.html.erb
<%= form_with(model: congregation, local: true) do |form| %>
  <% if congregation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(congregation.errors.count, "error") %> prohibited this congregation from being saved:</h2>

      <ul>
        <% congregation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :congregation_number %>
    <%= form.text_field :congregation_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/congregations/edit.html.erb
<h1>Editing Congregation</h1>

<%= render 'form', congregation: @congregation %>

<%= link_to 'Show', @congregation %> |
<%= link_to 'Back', congregations_path %>

app/views/congregations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Congregations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Congregation number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @congregations.each do |congregation| %>
      <tr>
        <td><%= congregation.name %></td>
        <td><%= congregation.congregation_number %></td>
        <td><%= link_to 'Show', congregation %></td>
        <td><%= link_to 'Edit', edit_congregation_path(congregation) %></td>
        <td><%= link_to 'Destroy', congregation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Congregation', new_congregation_path %>

app/views/congregations/new.html.erb
<h1>New Congregation</h1>

<%= render 'form', congregation: @congregation %>

<%= link_to 'Back', congregations_path %>

app/views/congregations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @congregation.name %>
</p>

<p>
  <strong>Congregation number:</strong>
  <%= @congregation.congregation_number %>
</p>

<%= link_to 'Edit', edit_congregation_path(@congregation) %> |
<%= link_to 'Back', congregations_path %>