config/routes.rb
Rails.application.routes.draw do
  root to: "souls#index"
  resources :public_talks
  resources :public_speakers
  resources :kingdom_halls
  resources :field_service_groups
  resources :congregations
  resources :contact_informations
  resources :publishers
  devise_for :users
  resources :souls
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/public_talk.rb
# frozen_string_literal: true
# Class that represents a collection of talk titles and corresponding data for each outline.
#
# Attributes:
# number - Integer, number of the outline
# public_talk_title - String, title of the outline
# public_talk_note - String, note from the outline
# revision_date - Date, month and year of outline revision
# file_pdf_url - String, location of outline as a pdf
# file_doc_url - String, location of outline as a doc
class PublicTalk < ApplicationRecord
  S99_PUBLIC_TALK_TITLES_PDF = 'storage/S-99-E.pdf'

  MANUAL_EDIT_TITLES = [29, 51, 71, 75, 76, 79, 104, 114, 119, 133, 153, 180, 194].freeze

  S99A_TALKS_BY_SUBJECT = {
    "Bible/God": [
      4, 26, 37, 54, 76, 80, 88, 99, 100, 101, 114, 124, 133, 137, 139, 145, 164, 169, 175, 187
    ],
    "Christian Standards/Qualities": [
      7, 10, 12, 14, 15, 48, 68, 69, 72, 77, 78, 103, 112, 144, 148, 157, 165, 171, 185
    ],
    "Evangelizing/Ministry": [
      17, 63, 66, 81
    ],
    "Faith/Spirituality": [
      1, 9, 16, 18, 22, 31, 39, 46, 67, 70, 71, 74, 87, 142, 147, 149, 151, 158, 159, 166, 68, 172, 188, 189, 192
    ],
    "Family/Youth": [
      5, 13, 27, 28, 29, 30, 104, 110, 113, 118, 146, 190
    ],
    "Kingdom/Paradise": [
      19, 21, 23, 24, 35, 42, 44, 47, 49, 60, 61, 62, 75, 85, 90, 91, 109, 111, 120, 122, 130, 132, 154, 162, 170, 174,
      180, 182
    ],
    "Last Days/God's Judgement": [
      2, 6, 20, 34, 38, 40, 41, 84, 93, 98, 102, 106, 108, 121, 150, 152, 153, 156, 176, 181, 193
    ],
    "Religion/Worship": [
      3, 8, 36, 43, 45, 52, 55, 56, 58, 82, 83, 86, 89, 92, 94, 95, 96, 125, 126, 127, 128, 129, 134, 135, 136, 140,
      155, 161, 163, 173
    ],
    "Trials/Problems": [
      32, 50, 57, 65, 73, 105, 117, 141, 143, 177, 184, 186, 194
    ],
    "World, No Part Of": [
      11, 33, 51, 53, 59, 64, 79, 97, 107, 115, 116, 119, 123, 131, 138, 160, 167, 178, 179, 183, 191
    ]
  }

  has_one_attached :s99_public_talk_titles_pdf
  has_one_attached :s99_public_talk_subjects_pdf
  has_many_attached :public_talk_pdf_outlines
  has_many_attached :public_talk_doc_outlines

  def process_public_talk_titles
    read_s99 = PDF::Reader.new(Rails.root.join(S99_PUBLIC_TALK_TITLES_PDF))

    read_s99.pages.each do |page|
      # Remove newlines, strip whitespace off titles, remove the document label, retunr array of arrays
      captured_outlines = page.text.delete!("\n").strip.gsub('S-99-E   10/18', '').scan(/(\d*)[.]\s(\D*)/)
      captured_outlines.each do |capture|
        next unless capture[0].to_i.positive? # need to remove introductory paragrpah on page 1, no number!

        @public_talk_number = capture[0].to_i
        @public_talk_title = capture[1].strip # some irrevernt space leftover...
        
        manually_edit_talk_titles(@public_talk_number) if MANUAL_EDIT_TITLES.include?(@public_talk_number)
        PublicTalk.create number: @public_talk_number, public_talk_title: @public_talk_title
      end
    end
  end

  # Scraped talk titles come with no spaces around hyphen, need to dress the hyphen up!
  def correctly_space_hyphen_in_title(public_talk_title)
    return unless /\p{Pd}/.match?(public_talk_title)

    @public_talk_title.gsub('-', ' - ') # this does not work right now...
  end

  # Scraped talk titles required some manual editing repeatedly.
  # TODO Need to see if this consistently happens on next S-99 iteration
  def manually_edit_talk_titles(public_talk_number)
    @public_talk_title = case public_talk_number
                         when 29
                           'Responsibilities and Rewards of Parenthood'
                         when 51
                           'Is the Truth Transforming Your Life?'
                         when 71
                           'How to Keep Spiritually Awake'
                         when 75
                           'Do You Recognize Jehovah’s Sovereignty in Your Personal Life?'
                         when 76
                           'Bible Principles—Can They Help Us to Cope With Today’s Problems?'
                         when 79
                           'Friendship With God, Friendship With the World—Which Will You Choose?'
                         when 104
                           'Parents—Are You Building With Fire-Resistant Materials?'
                         when 114
                           'Appreciating Marvels of God’s Creation'
                         when 119
                           'Christian Separateness From the World—Why Beneﬁcial'
                         when 133
                           'The Origin of Humans—Does It Matter What You Believe?'
                         when 153
                           'Keep Close in Mind the “Fear-Inspiring Day”!'
                         when 180
                           'The Resurrection—Why That Hope Should Be Real to You'
                         when 194
                           'How Godly Wisdom Beneﬁts Us'
                         end
  end
end

app/models/public_talk/s99_pdf_hacker.rb
# frozen_string_literal: true 

module PublicTalk
  class S99PdfHacker
    # Temporary resting spot for implementaion
    local_titles_file = '/Users/jw/dev/scripts/s99_pdf_hacker/S-99-E.pdf'
    local_subjects_file = '/Users/jw/dev/scripts/s99_pdf_hacker/S-99a-E.pdf'

    # Regex for talk number and talk title lines
    TALK_NUMBER_TITLE_REGEX = /\A.\s*\d{1,2}.\s/

    # Regex for talk number
    TALK_NUMBER_REGEX = /.\s*(\d*).\s(.*)/

    # Regex for talk title
    TALK_TITLE_REGEX = /.\s*(\d*).\s(.*)/

    # Manually created due to regex overwhelimg...
    talk_subject_mapping = {
      'Bible/God': %w[
        4 26 37 54 76 80 88 99 100 101 114 124 133 137 139 145 164 169 175 187
      ],
      'Christian Standards/Qualities': %w[
        7 10 12 14 15 48 68 69 72 77 78 103 112 144 148 157 165 171 185
      ],
      'Evangelizing/Ministry': %w[17 63 66 81],
      'Faith/Spirituality': %w[1 9 16 18 22 31 39 46 67 70 71 74 87 ],
      'Family/Youth': [],
      'Kingdom/Paradise': [],
      'Last Days/God\'s Judgement': [],
      'Religion/Worship': [],
      'Trials/Problems': [],
      'World, No Part Of': []
    }

    

    # attr_accessorto access without @ in class
    attr_accessor :public_talk_number
    attr_accessor :public_talk_title
    attr_accessor :public_talk_subject

    talks_array = []

    def initialize()

    end

    # Method will rip though the S99 title pdf anf collect talk numbers and titles.
    # Will return an array if arrays of talk numbers and titles, that way we can add 
    # subjet later before writing to database.
    def hack_the_titles_pdf
      read_data = PDF::Reader.new(local_titles_file)
      pdf_page_count = read_data.page_count

      pdf_page_count.times do |iteration|
        next if iteration == 0 # 0 based iteration is useless
        page_text = read_data.page(iteration).text
        page_text.lines.each do |line|
          if TALK_NUMBER_TITLE_REGEX.match?(line)
            talk_number = TALK_NUMBER_REGEX.match(line)[1].to_i
            talk_title = TALK_TITLE_REGEX.match(line)[2]
            paired_data = [talk_number, talk_title]
            talks_array << paired_data
          end
        end
      end
    end

    def hack_subjects_pdf
      read_data = PDF::Reader.new(local_titles_file)
      pdf_page_count = read_data.page_count
    end
  end
end

app/controllers/public_talks_controller.rb
class PublicTalksController < ApplicationController
  before_action :set_public_talk, only: [:show, :edit, :update, :destroy]

  # GET /public_talks
  # GET /public_talks.json
  def index
    @public_talks = PublicTalk.all
  end

  # GET /public_talks/1
  # GET /public_talks/1.json
  def show
  end

  # GET /public_talks/new
  def new
    @public_talk = PublicTalk.new
  end

  # GET /public_talks/1/edit
  def edit
  end

  # POST /public_talks
  # POST /public_talks.json
  def create
    @public_talk = PublicTalk.new(public_talk_params)

    respond_to do |format|
      if @public_talk.save
        format.html { redirect_to @public_talk, notice: 'Public talk was successfully created.' }
        format.json { render :show, status: :created, location: @public_talk }
      else
        format.html { render :new }
        format.json { render json: @public_talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /public_talks/1
  # PATCH/PUT /public_talks/1.json
  def update
    respond_to do |format|
      if @public_talk.update(public_talk_params)
        format.html { redirect_to @public_talk, notice: 'Public talk was successfully updated.' }
        format.json { render :show, status: :ok, location: @public_talk }
      else
        format.html { render :edit }
        format.json { render json: @public_talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /public_talks/1
  # DELETE /public_talks/1.json
  def destroy
    @public_talk.destroy
    respond_to do |format|
      format.html { redirect_to public_talks_url, notice: 'Public talk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_public_talk
    @public_talk = PublicTalk.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def public_talk_params
    params.require(:public_talk).permit(
      :number, :public_talk_title, :public_talk_note, :revision_date, :file_pdf_url, :file_doc_url,
      :s99_public_talk_titles_pdf, :s99_public_talk_subjects_pdf,
      public_talk_pdf_outlines: [], public_talk_doc_outlines: []
    )
  end
end

app/helpers/public_talks_helper.rb
module PublicTalksHelper
end

app/views/public_talks/_form.html.erb
<%= form_with(model: public_talk, local: true) do |form| %>
  <% if public_talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(public_talk.errors.count, "error") %> prohibited this public_talk from being saved:</h2>

      <ul>
        <% public_talk.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :public_talk_title %>
    <%= form.text_field :public_talk_title %>
  </div>

  <div class="field">
    <%= form.label :public_talk_note %>
    <%= form.text_field :public_talk_note %>
  </div>

  <div class="field">
    <%= form.label :revision_date %>
    <%= form.date_select :revision_date %>
  </div>

  <div class="field">
    <%= form.label :file_pdf_url %>
    <%= form.text_field :file_pdf_url %>
  </div>

  <div class="field">
    <%= form.label :file_doc_url %>
    <%= form.text_field :file_doc_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/public_talks/edit.html.erb
<h1>Editing Public Talk</h1>

<%= render 'form', public_talk: @public_talk %>

<%= link_to 'Show', @public_talk %> |
<%= link_to 'Back', public_talks_path %>

app/views/public_talks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Public Talks</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Public talk title</th>
      <th>Public talk note</th>
      <th>Revision date</th>
      <th>File pdf url</th>
      <th>File doc url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @public_talks.each do |public_talk| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><%= public_talk.number %></td>
        <td><%= public_talk.public_talk_title %></td>
        <td><%= public_talk.public_talk_note %></td>
        <td><%= public_talk.revision_date %></td>
        <td><%= public_talk.file_pdf_url %></td>
        <td><%= public_talk.file_doc_url %></td>
        <td><%= link_to 'Show', public_talk %></td>
        <td><%= link_to 'Edit', edit_public_talk_path(public_talk) %></td>
        <td><%= link_to 'Destroy', public_talk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Public Talk', new_public_talk_path %>

app/views/public_talks/new.html.erb
<h1>New Public Talk</h1>

<%= render 'form', public_talk: @public_talk %>

<%= link_to 'Back', public_talks_path %>

app/views/public_talks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @public_talk.number %>
</p>

<p>
  <strong>Public talk title:</strong>
  <%= @public_talk.public_talk_title %>
</p>

<p>
  <strong>Public talk note:</strong>
  <%= @public_talk.public_talk_note %>
</p>

<p>
  <strong>Revision date:</strong>
  <%= @public_talk.revision_date %>
</p>

<p>
  <strong>File pdf url:</strong>
  <%= @public_talk.file_pdf_url %>
</p>

<p>
  <strong>File doc url:</strong>
  <%= @public_talk.file_doc_url %>
</p>

<%= link_to 'Edit', edit_public_talk_path(@public_talk) %> |
<%= link_to 'Back', public_talks_path %>