config/routes.rb
Rails.application.routes.draw do
  root to: "souls#index"
  resources :public_talks
  resources :public_speakers
  resources :kingdom_halls
  resources :field_service_groups
  resources :congregations
  resources :contact_informations
  resources :publishers
  devise_for :users
  resources :souls
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/public_speaker.rb
class PublicSpeaker < ApplicationRecord
  belongs_to :congregation
  belongs_to :publisher
end

app/controllers/public_speakers_controller.rb
class PublicSpeakersController < ApplicationController
  before_action :set_public_speaker, only: [:show, :edit, :update, :destroy]

  # GET /public_speakers
  # GET /public_speakers.json
  def index
    @public_speakers = PublicSpeaker.all
  end

  # GET /public_speakers/1
  # GET /public_speakers/1.json
  def show
  end

  # GET /public_speakers/new
  def new
    @public_speaker = PublicSpeaker.new
  end

  # GET /public_speakers/1/edit
  def edit
  end

  # POST /public_speakers
  # POST /public_speakers.json
  def create
    @public_speaker = PublicSpeaker.new(public_speaker_params)

    respond_to do |format|
      if @public_speaker.save
        format.html { redirect_to @public_speaker, notice: 'Public speaker was successfully created.' }
        format.json { render :show, status: :created, location: @public_speaker }
      else
        format.html { render :new }
        format.json { render json: @public_speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /public_speakers/1
  # PATCH/PUT /public_speakers/1.json
  def update
    respond_to do |format|
      if @public_speaker.update(public_speaker_params)
        format.html { redirect_to @public_speaker, notice: 'Public speaker was successfully updated.' }
        format.json { render :show, status: :ok, location: @public_speaker }
      else
        format.html { render :edit }
        format.json { render json: @public_speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /public_speakers/1
  # DELETE /public_speakers/1.json
  def destroy
    @public_speaker.destroy
    respond_to do |format|
      format.html { redirect_to public_speakers_url, notice: 'Public speaker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_public_speaker
      @public_speaker = PublicSpeaker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def public_speaker_params
      params.fetch(:public_speaker, {})
    end
end

app/helpers/public_speakers_helper.rb
module PublicSpeakersHelper
end

app/views/public_speakers/_form.html.erb
<%= form_with(model: public_speaker, local: true) do |form| %>
  <% if public_speaker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(public_speaker.errors.count, "error") %> prohibited this public_speaker from being saved:</h2>

      <ul>
        <% public_speaker.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/public_speakers/edit.html.erb
<h1>Editing Public Speaker</h1>

<%= render 'form', public_speaker: @public_speaker %>

<%= link_to 'Show', @public_speaker %> |
<%= link_to 'Back', public_speakers_path %>

app/views/public_speakers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Public Speakers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @public_speakers.each do |public_speaker| %>
      <tr>
        <td><%= link_to 'Show', public_speaker %></td>
        <td><%= link_to 'Edit', edit_public_speaker_path(public_speaker) %></td>
        <td><%= link_to 'Destroy', public_speaker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Public Speaker', new_public_speaker_path %>

app/views/public_speakers/new.html.erb
<h1>New Public Speaker</h1>

<%= render 'form', public_speaker: @public_speaker %>

<%= link_to 'Back', public_speakers_path %>

app/views/public_speakers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_public_speaker_path(@public_speaker) %> |
<%= link_to 'Back', public_speakers_path %>